### ISSUE TITLE
Swap the production branch from `master` to `main`

### ISSUE THREAD

**Issue by bethaniley** [forrtproject/forrtproject.github.io#122]
**Is your feature request related to a problem? Please describe.**
`master` branch is a historic term which was phased out by GitHub in 2020. This was to [improve cultual sensitivity](https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main) and [embed anti-racism in coding practices](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6148600/), as it originates from "master/slave" terminology.

**Describe the solution you'd like**
Convert the production branch to `main` from `master`.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by DAKiersz** [comment]
We will combine this with changes that will reduce the repository size.
