### ISSUE TITLE
Update Google Analytics

### ISSUE THREAD

**Issue by bethaniley** [forrtproject/forrtproject.github.io#123]
**Is your feature request related to a problem? Please describe.**
Universal Analytics is sunsetting on 1st July 2024.

**Describe the solution you'd like**
[Migration to Google Analytics 4](https://support.google.com/analytics/answer/11583528?hl=en).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by DAKiersz** [comment]
#128 relevant PR

**Comment by DAKiersz** [comment]
This was completed by myself and @bethaniley and linked to FORRT's new Analytics page.
