### ISSUE TITLE
Glossary reference not showing correctly

### ISSUE THREAD

**Issue by LukasRoeseler** [forrtproject/forrtproject.github.io#138]
**Describe the bug**
Link to related terms is missing a part.
In the glossary it says: _Related terms: <a href='/glossary/anonymity/'>Anonymity</a>,_

**To Reproduce**
1. Go [here](https://forrt.org/glossary/amnesia/)

**Expected behavior**
Probably add something like "forrt.org" before the link

**Screenshots**
![image](https://github.com/forrtproject/forrtproject.github.io/assets/117925406/b2ed3be3-e601-4ffe-a0e2-d2e3e023da51)

**Comment by LukasWallrich** [comment]
Thanks, but duplicates #132
