### ISSUE TITLE
Reducing reviews required for a PR from 1 to 2 for content folder

### ISSUE THREAD

**Issue by flavioazevedo** [forrtproject/forrtproject.github.io#146]
We should probably discuss the several changes in how the website works in detail sometime after the summer, but I would like to request for the moment that only one review is necessary to facilitate the speed with which we are able to fix bugs on the website for content changes, add content, remove wrong info, add talks and partnerships, etc.

See, for example, this case where a forrt member is unable to use FORRT glossary in their training, and this is time-sensitive, and there are folks willing work on the weekend to fix the issue:

https://forrt.slack.com/archives/CM6344P5E/p1720808081180659?thread_ts=1720808081.180659&cid=CM6344P5E

**Comment by bethaniley** [comment]
Hi Flavio! I believe I explained this change to you in the meeting we had when Dominik and I changed the GitHub Organisation structure. Apologies if I didn't communicate it clearly enough.

The reason we changed this to two reviewers was to prevent changes which break the website. A lot of previous approvals have been "looks good to me" approvals, in the sense that the person reviewing doesn't seem to check the code, or even outright admits that they [don't know whether the untested code will work](https://github.com/forrtproject/forrtproject.github.io/pull/133#pullrequestreview-2160829882). As part of the IOI grant, we reviewed this and identified it as a potential weak point for future releases.

The vision for the two-person review system is that there would be:
1. **One technical reviewer** - someone who understands the code and can actually check it. That is generally performed by myself, Dominik K., Sam G., Richard D., or Lukas W.
2. **One conceptual reviewer** - does the proposed change make sense for FORRT's mission/vision? This generally comes from yourself, but can be done by anyone in FORRT's management.

You can think of this as analogous to peer review of a journal article. If they don't understand the conceptual framing and methodology, are they actually reviewing the paper?

**Comment by bethaniley** [comment]
Duplicate issue with #136
