### ISSUE TITLE
About FORRT > FORRT's principles opens an empty page

### ISSUE THREAD

**Issue by SamGuay** [forrtproject/forrtproject.github.io#36]
Title says it all. Probably a wrong URL in the menu settings.

**Comment by flavioazevedo** [comment]
Here's the .md

+++
# A Demo section created with the Blank widget.
# Any elements can be added in the body: https://sourcethemes.com/academic/docs/writing-markdown-latex/
# Add more sections by duplicating this file and customizing to your requirements.

widget = "blank"  # See https://sourcethemes.com/academic/docs/page-builder/
headless = true  # This file represents a page section.
active = true  # Activate this widget? true/false
weight = 20  # Order that this section will appear.

title = "FORRT's principles"
subtitle = ""
classtitle = "text-center"

[design]
  # Choose how many columns the section has. Valid values: 1 or 2.
  columns = "1"

[design.background]
  # Apply a background color, gradient, or image.
  #   Uncomment (by removing `#`) an option to apply it.
  #   Choose a light or dark text color by setting `text_color_light`.
  #   Any HTML color name or Hex value is valid.

  # Background color.
   color = "#fefdf6"
  # color = "#69b3a2" # greenish
  
  # Background gradient.
  # gradient_start = "DeepSkyBlue"
  # gradient_end = "SkyBlue"
  
  # Background image.
  # image = "headers/bubbles-wide.jpg"  # Name of image in `static/img/`.
  # image_darken = 0.6  # Darken the image? Range 0-1 where 0 is transparent and 1 is opaque.
  # image_size = "cover"  #  Options are `cover` (default), `contain`, or `actual` size.
  # image_position = "center"  # Options include `left`, `center` (default), or `right`.
  # image_parallax = true  # Use a fun parallax-like fixed background effect? true/false

  # Text color (true=light or false=dark).
  text_color_light = false

[design.spacing]
  # Customize the section spacing. Order is top, right, bottom, left.
  padding = ["60px", "0", "60px", "0"]


[advanced]
 # Custom CSS. 
 css_style = ""
 
 # CSS class.
 css_class = ""

+++

# Principles

## Principled Teaching 

We believe it is of utmost importance to communicate the facts of science relative to the process by which it was acquired. Scientific claims should be taken in light of epistemic uncertainty – i.e., the intrinsic incertitude about the validity of truth claims (including scientific), to avoid teaching students a false sense of certainty about ‘the facts’ of science. This idea is enshrined at the core of the open science movement, the credibility revolution, open access, and better measurement practices.

### Advantages of principled teaching:
* it exposes students to a more honest educational process, especially with respect to epistemic uncertainty and its consequences to the facts of science; 
* it bequeaths first-hand practical experience in probing the production of knowledge which in turn trains students to be good consumers of science; 
{{< expand "Expand to know more" >}}
An increasing number of scholars have incorporated reproducible, transparent, and open principles to their research pipeline. However, the associated social and ethical responsibilities towards the teaching of these principles is yet to be realized. It is still common practice to teach subject matters, at undergraduate and graduate levels, for quantitative and qualitative science, without resolutely emphasizing that scientific claims should be taken in light of epistemic uncertainty – i.e., the intrinsic incertitude about the validity of truth claims (including scientific). This has the unfortunate consequence of teaching students a false sense of certainty about ‘the facts’ of science, which can be thought of as misleading, if not unethical.
{{< /expand >}}


## Principled Mentoring
 
Central to the academic ethos, the relationship between mentor and mentee is one of scientific genesis, incremental contributions, and personal and professional development. This academic experience is optimized when students feel they can contribute to the supervisor’s research and the product of this contribution is valued. One way to achieve this is to expose students to  the intricacies and procedures of science making, including the flaws and merits of any given research approach. Open and reproducible tenets serve an important role in mentorship pedagogy.

### Advantages of principle mentoring:
* it enables students to see their work and efforts serve a meaningful practical purpose: to aggregate and positively impact the scientific community
* it breeds an atmosphere of constructive curiosity and problem-solving; 
* it endows students with the ability to discover on their own the myriad of ways their skill set and ability can be integrated into the research * process. 
* it helps shatter the academic glass ceiling and promote engagement with the academic profession.
* it galvanizes and accelerates the dissemination of reliable, rigorous, replicable, open, reproducible science to a previously uninformed population: undergraduate and graduate students.

**Comment by axrhart** [comment]
@SamGuay There is no url parameter in the index.md

**Comment by flavioazevedo** [comment]
If it is easier @SamGuay @axrhart here are the files :) 

[index.md](https://github.com/forrtproject/forrtproject.github.io/files/6863696/index.md)
[principles.md](https://github.com/forrtproject/forrtproject.github.io/files/6863697/principles.md)

**Comment by SamGuay** [comment]
Hugo usually doesnt need the URL param. It's just in config/_default/menu, you can see the problem. It's a quick fix. 

PS: Alex 1, Flavio 0 :laughing:
