### ISSUE TITLE
Find alternative solution to netlify form

### ISSUE THREAD

**Issue by SamGuay** [forrtproject/forrtproject.github.io#38]
Since we are moving away from netlify, we need another solution for the subscription form. 
Will think about it later. 
Maybe a simple tinyletter?

**Comment by axrhart** [comment]
What is the subscription for supposed to do? Sending an email oder garther data in the database?

Either way, if we decide on a WebHosting/VPS for the wiki we could set up our own form there and iframe it to the site.
