### ISSUE TITLE
Make "Get involved" page more prominent.

### ISSUE THREAD

**Issue by NunoSempere** [forrtproject/forrtproject.github.io#41]
Right now, it isn't very prominent, but it should be!

**Comment by flavioazevedo** [comment]
@SamGuay How can we achieve this Sam? Any thoughts on Nuno's suggestion?

**Comment by TuringTux** [comment]
Apologies for hijacking this thread, I just stumbled upon it randomly and thought I could contribute something:

Maybe adding a button to the navigation bar could help, something like this?

![Navbar of forrt.org, with a blue "Get involved" button inserted to the left of the search icon](https://user-images.githubusercontent.com/53300311/201643000-884d7fc2-7b7e-458e-9b46-f0c6afdbb8aa.png)

I think that type of button is pretty common for sites that want a user to do something (sign up, contact sales etc.), and I suppose it is also quite effective.

**Comment by flavioazevedo** [comment]
Sorry for the delay. I like this @TuringTux! Would you like to implement it, please?

**Comment by TuringTux** [comment]
I will definitely try, not sure how fast I'll get to it though :)
