### ISSUE TITLE
Link to theme in footer goes to spam site

### ISSUE THREAD

**Issue by da5nsy** [forrtproject/forrtproject.github.io#77]
**Describe the bug**

The link labeled "Academic theme" goes to https://sourcethemes.com/academic/, which looks to be a spam site.

**Comment by richarddushime** [comment]
i saw it too , i could fix it  @da5nsy @flavioazevedo anything else i should consider ?

**Comment by flavioazevedo** [comment]
Thank you @da5nsy and @richarddushime ! You are 100% correct! they changed the website and it looks as if as it is this one: https://wowchemy.com
